

pipeline {
  agent any
  stages {
    stage('Build'){
      steps{
      echo 'Download dependencies'
        withMaven(maven:"maven-387", publisherStrategy: 'EXPLICIT'){
          sh "cd api \n\
          mvn install -P default"
          }
        }
    }
    stage('Static code analysis'){
        steps{
        script{
            echo 'Static code analysis'
            sh "cd api\n\
              mvn install -P static-code-analysis\n\
              echo \"static code analysis finished\""
            }
            
            echo "Reading static analysis report"
            recordIssues enabledForFailure: true, failOnError: false, tool:checkStyle(pattern: "**/target/checkstyle-result.xml")
//             recordIssues enabledForFailure: true, failOnError: false, tool:findBugs(pattern: "**/target/findbugs*.xml")
            recordIssues enabledForFailure: true, failOnError: false, tool:cpd(pattern: "**/target/cpd.xml")
            recordIssues enabledForFailure: true, failOnError: false, tool:pmdParser(pattern: "**/target/pmd.xml")
            }
          }        

    stage('Test'){
          steps{
            script{
                echo 'Test'
                sh "cd api\n\
                mvn install -P tests"
                }
                
                publishHTML([
                  allowMissing: true,
                  keepAll:true,
                  alwaysLinkToLastBuild: true,
                  reportDir: 'api/target/site/jacoco',
                  reportFiles: 'index.html',
                  reportName: 'Jacoco coverage HTML report'])
             }        
    }
  }
}